import type { Metadata } from "next";
import { PlacementDashboard } from "@/components/PlacementDashboard";
import { PageHero, SourceLink } from "@/components/ui";
import { images } from "@/data/assets";
import { placementSource } from "@/data/placements";
import { pageMetadata } from "@/data/seo";

export const metadata: Metadata =pageMetadata("FISAT Placements & Career Pathways","Review FISAT's year-wise placement information with source notes, historical package and company figures and a link to the current official placement record.");
export default function PlacementsPage(){return <><PageHero eyebrow="Careers · Placement & Training" title="FROM CAMPUS TO CAREER." description="A transparent look at official cohort outcomes, historical results and career preparation at FISAT." image={images.industry} crumbs={[{label:"Placements"}]}/><section className="section"><div className="container"><div className="placements-lead"><div><p className="eyebrow"><span/>Opportunity with context</p><h2>Careers begin<br/><em>with preparation.</em></h2></div><div><p>Compare the official placement record by batch. Each number is dated or qualified. Where the current public summary is inconsistent, the dashboard states that clearly instead of guessing.</p><SourceLink href={placementSource} label="Current FISAT placements page"/></div></div><PlacementDashboard/></div></section><section className="section section--paper"><div className="container placement-training"><div><p className="eyebrow"><span/>Beyond the offer letter</p><h2>Build confidence<br/>for the next step.</h2><p>FISAT describes soft-skills development, regular tests, group discussions, mock interviews, competitive-exam guidance and support from industry experts through its Placement and Training Cell.</p><SourceLink href={placementSource} label="Placement training and career guidance"/></div><img src={images.industry} alt="FISAT students preparing for campus recruitment" loading="lazy"/></div></section></>;}
