import type { Metadata } from "next";
import { Activity, Dumbbell, ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { PageHero, SectionHeading, SourceLink } from "@/components/ui";
import { images } from "@/data/assets";
import { pageMetadata } from "@/data/seo";

const spaces=["Fitness Centre", "Football", "Cricket", "Basketball", "Volleyball", "Badminton", "Table tennis", "Athletics"];
export const metadata: Metadata =pageMetadata("FISAT Fitness Centre, Sports & Games","Explore FISAT's Fitness Centre, gymnasium and sports facilities. Confirm current activities, access and schedules directly with the institution.");
export default function FitnessPage(){return <><PageHero eyebrow="Facilities · Movement" title="TRAIN HARD. LIVE WELL." description="Find space for fitness, sports and wellbeing on the FISAT campus." image={images.fitness} crumbs={[{label:"Facilities",href:"/facilities"},{label:"Fitness & sports"}]}/><section className="section"><div className="container"><div className="fitness-story"><div className="fitness-story__copy"><p className="eyebrow"><span/>Training · Sport · Wellbeing</p><h2>Make room<br/><em>to move.</em></h2><p>FISAT lists a gymnasium, Fitness Centre, stadium, and sports and games among its campus facilities. Ask the institution about current equipment, activities, access and opening times.</p><SourceLink href="https://fisat.ac.in/fitness-centre/" label="FISAT Fitness Centre information"/></div><div className="fitness-story__image"><img src={images.sports} alt="Sports and activity on the FISAT campus" loading="lazy"/></div></div><div className="sports-listing"><SectionHeading eyebrow="Find your field" title="Ways to move at FISAT." description="Activities listed for the campus in the brief; check current facilities and programme availability with FISAT."/><div className="sports-activity-grid">{spaces.map((item,index)=><div key={item}><span>0{index+1}</span><strong>{item}</strong><Activity size={16}/></div>)}</div><p className="activity-note">Activity facilities and schedules can change by season and campus access. Contact FISAT before planning use.</p><div className="sports-links"><Link href="/facilities/sports">Explore sports & games<ArrowUpRight size={15}/></Link><Link href="/contact">Contact FISAT<ArrowUpRight size={15}/></Link><SourceLink href="https://fisat.ac.in/facility/sports-and-games/" label="Official sports and games directory"/></div></div></div></section></>;}
